spring:
  application:
    name: auth-assignment

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
  secrets:
    secretKey: ${SECRET_KEY}
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true